{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel",
    "version": "2.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-2.8.7-multiplatform-sources.jar",
          "url": "lifecycle-viewmodel-2.8.7-multiplatform-sources.jar",
          "size": 51073,
          "sha512": "41c68f61e13b941aced9e4677146bd5a2e63896a13141b5b9d5869f3feff033a9cbb8a532445e2d7634751abe30c3f6f2145d4d4a4e12b11863cce7337611d7a",
          "sha256": "2ccb141fc419a97721cf8cc71ec4e6204be9c8b9697ebf9237195818ffca5048",
          "sha1": "4251104b19d8213d3b3b0da507503b93b27f084e",
          "md5": "ad3dd4ffc50227a0ede1aaf4cbdfad68"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "lifecycle-viewmodel-2.8.7-versionMetadata.json",
          "size": 9519,
          "sha512": "99e70a8deba798b359d39b21b6513ad761f62b7a18c18b9ca6ec3deb8b32e5587b63ec9be96fdd2529fa15dc3a558a5e89aa153513a1509ff476fbc06da4bd36",
          "sha256": "91398760d00a348b55c4f27c186c7987aa409313479b93cdbdd93ef5468e89cd",
          "sha1": "5dc35b25b76b98d8833c82092c724ec44d61aaec",
          "md5": "9e437cc98e3975911a5d3d0baaa4525d"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-metadata-2.8.7.jar",
          "url": "lifecycle-viewmodel-2.8.7.jar",
          "size": 20092,
          "sha512": "6427b4fd81cd7ff1251739d578690abb9324325570c7734b252fdf6a1dc1d351aa058e9cc52b055e6fcd67234681ff4ed28420351be66f2edc744ed25b37add0",
          "sha256": "539281344ce8a81d33570be300d86bb872c7b719a6dd2ce494eacba438fb53ce",
          "sha1": "5b3d6677fe81e9ce690f0759c11506b277f84a9c",
          "md5": "512b0b50ab9dff3cf3d1b291e5faa39d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.7"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-kotlin-2.8.7-sources.jar",
          "url": "lifecycle-viewmodel-2.8.7-sources.jar",
          "size": 36605,
          "sha512": "22b2d261532b6f4107bd25fe731abb909d6b5517acf4d84099d3c911146066785432943fb49ae7246a6736ea7b16c71b081f3054067c38ca1739ca89db3365ed",
          "sha256": "f4fd0d6b5980d0b3b76229068222c00ce1946f808413ac62adae5d78cf62cde8",
          "sha1": "e7613a0602a2791cc6b34c155adebadfed679d13",
          "md5": "554fb53c99b47e759562ff7f50998c4e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-android/2.8.7/lifecycle-viewmodel-android-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-android",
        "version": "2.8.7"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-android/2.8.7/lifecycle-viewmodel-android-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-android",
        "version": "2.8.7"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-android/2.8.7/lifecycle-viewmodel-android-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-android",
        "version": "2.8.7"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-desktop/2.8.7/lifecycle-viewmodel-desktop-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-desktop",
        "version": "2.8.7"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-desktop/2.8.7/lifecycle-viewmodel-desktop-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-desktop",
        "version": "2.8.7"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-desktop/2.8.7/lifecycle-viewmodel-desktop-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-desktop",
        "version": "2.8.7"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-iosarm64/2.8.7/lifecycle-viewmodel-iosarm64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-iosarm64",
        "version": "2.8.7"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-iosarm64/2.8.7/lifecycle-viewmodel-iosarm64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-iosarm64",
        "version": "2.8.7"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-iosarm64/2.8.7/lifecycle-viewmodel-iosarm64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-iosarm64",
        "version": "2.8.7"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-iossimulatorarm64/2.8.7/lifecycle-viewmodel-iossimulatorarm64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-iossimulatorarm64",
        "version": "2.8.7"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-iossimulatorarm64/2.8.7/lifecycle-viewmodel-iossimulatorarm64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-iossimulatorarm64",
        "version": "2.8.7"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-iossimulatorarm64/2.8.7/lifecycle-viewmodel-iossimulatorarm64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-iossimulatorarm64",
        "version": "2.8.7"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-iosx64/2.8.7/lifecycle-viewmodel-iosx64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-iosx64",
        "version": "2.8.7"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-iosx64/2.8.7/lifecycle-viewmodel-iosx64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-iosx64",
        "version": "2.8.7"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-iosx64/2.8.7/lifecycle-viewmodel-iosx64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-iosx64",
        "version": "2.8.7"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-linuxx64/2.8.7/lifecycle-viewmodel-linuxx64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-linuxx64",
        "version": "2.8.7"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-linuxx64/2.8.7/lifecycle-viewmodel-linuxx64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-linuxx64",
        "version": "2.8.7"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-macosarm64/2.8.7/lifecycle-viewmodel-macosarm64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-macosarm64",
        "version": "2.8.7"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-macosarm64/2.8.7/lifecycle-viewmodel-macosarm64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-macosarm64",
        "version": "2.8.7"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-macosarm64/2.8.7/lifecycle-viewmodel-macosarm64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-macosarm64",
        "version": "2.8.7"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-macosx64/2.8.7/lifecycle-viewmodel-macosx64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-macosx64",
        "version": "2.8.7"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-macosx64/2.8.7/lifecycle-viewmodel-macosx64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-macosx64",
        "version": "2.8.7"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-macosx64/2.8.7/lifecycle-viewmodel-macosx64-2.8.7.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-macosx64",
        "version": "2.8.7"
      }
    }
  ]
}