{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji2",
    "module": "emoji2-views-helper",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker-samples",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-benchmark",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.3.0.aar",
          "url": "emoji2-views-helper-1.3.0.aar",
          "size": 22075,
          "sha512": "1c5ebe19d91cd3491454de9e12615f94ed1e6e49fd97ab02709aa2e5bfeb27a89d20148854503e255c5fbbdc7d77ad5ac9cd3e5b902817ed1f32e5b0178c58ca",
          "sha256": "9a1351295a4f739df0efe8344adaa9afb34856c3af584d4a9afbec105a45b90b",
          "sha1": "7bef7c1117bb40ef41ee0641cd1d2d605e2d607c",
          "md5": "473586f500e1ae30491f2cf67dd13870"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker-samples",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-benchmark",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.3.0.aar",
          "url": "emoji2-views-helper-1.3.0.aar",
          "size": 22075,
          "sha512": "1c5ebe19d91cd3491454de9e12615f94ed1e6e49fd97ab02709aa2e5bfeb27a89d20148854503e255c5fbbdc7d77ad5ac9cd3e5b902817ed1f32e5b0178c58ca",
          "sha256": "9a1351295a4f739df0efe8344adaa9afb34856c3af584d4a9afbec105a45b90b",
          "sha1": "7bef7c1117bb40ef41ee0641cd1d2d605e2d607c",
          "md5": "473586f500e1ae30491f2cf67dd13870"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker-samples",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-benchmark",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.3.0-sources.jar",
          "url": "emoji2-views-helper-1.3.0-sources.jar",
          "size": 17409,
          "sha512": "9c16707fa7227ef6ff5dd22db1a50b2c046f4da9d6e719cce0650214c8fe430112fa217c0058b09b66488533b03f514710b056b8fc33198ccef8e4e0a8ce2489",
          "sha256": "ae8f9eac6a0627a136f631af717e6fab86a69e45c83765661e3795f7bbef3562",
          "sha1": "070bc75b8c5681fc8d0a4026648950c1cfd90a72",
          "md5": "71eca72934c7840028ba5480a3f5c33e"
        }
      ]
    }
  ]
}