{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.profileinstaller",
    "module": "profileinstaller",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "profileinstaller-1.4.0-sources.jar",
          "url": "profileinstaller-1.4.0-sources.jar",
          "size": 44238,
          "sha512": "6535656d2f1d25ed6a5759833f3a773ac9b6fbbaf1c54ca9446d9b669d4ad8c6e5b9e8a3d29c6c3cf3bb7a1e78b35a68b6f75969fb3bd1d5c51977e716108a59",
          "sha256": "7b8637080b47188656fd54dab66e9270334242d277d2a8e3c46691c3afa152a0",
          "sha1": "d126d45c480aa74f73ba5bee34a7217f6382c44a",
          "md5": "65216fb7a55f50e1dba7b5433772b057"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "profileinstaller-1.4.0.aar",
          "url": "profileinstaller-1.4.0.aar",
          "size": 53890,
          "sha512": "601213c32b7f02626667571353d1d94fa16e3227d7b4f2026d02b87af6732a7b5dd274c9b7a4f160faa0a324f64fb753de5a46bed66cb0c92094ba89e896d1f6",
          "sha256": "d502141fcce902430f62b674c32aecd0f75262e7ee2cd15c74adb617cd13130a",
          "sha1": "6b6262e9ca50d1f75a496f3b64ebeb092a9d42eb",
          "md5": "aa5fc2586d48606b754f98f5cedf9f55"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "profileinstaller-1.4.0.aar",
          "url": "profileinstaller-1.4.0.aar",
          "size": 53890,
          "sha512": "601213c32b7f02626667571353d1d94fa16e3227d7b4f2026d02b87af6732a7b5dd274c9b7a4f160faa0a324f64fb753de5a46bed66cb0c92094ba89e896d1f6",
          "sha256": "d502141fcce902430f62b674c32aecd0f75262e7ee2cd15c74adb617cd13130a",
          "sha1": "6b6262e9ca50d1f75a496f3b64ebeb092a9d42eb",
          "md5": "aa5fc2586d48606b754f98f5cedf9f55"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "profileinstaller-1.4.0-versionMetadata.json",
          "url": "profileinstaller-1.4.0-versionMetadata.json",
          "size": 4104,
          "sha512": "7b5c884ed7c9b4300adf494bb274281d71d1b9ea6d30ba784307e7c7f0ea38bcfeb5b97e71eb5c3633d988819b744e4c971a2081a063caee29bedd7e9500496e",
          "sha256": "754ac09f694c8cf4992edb24ca0e22b52bc524eda89352613728a6e514176904",
          "sha1": "c65d2e31cf641a3f658ac5532d1f724fa8f3dd3e",
          "md5": "93c1aa592a96bb4442d442606b636210"
        }
      ]
    }
  ]
}