{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.concurrent",
    "module": "concurrent-futures",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId:": "6739212"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "concurrent-futures-1.1.0.jar",
          "url": "concurrent-futures-1.1.0.jar",
          "size": 25987,
          "sha512": "3864ec1769828064e1002d4319ed5d275de29a54c6150f47decb5e2afff5b4216faa5eace49f6e95121bff580d07a3e4121c9fdbc84113694c86df4bd655214d",
          "sha256": "0ce067c514a0d1049d1bebdf709e344ed3266fe9744275682937cdcb13334e9e",
          "sha1": "50b7fb98350d5f42a4e49704b03278542293ba48",
          "md5": "409aee996eabfb4f23428b2d6026d6aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "concurrent-futures-1.1.0.jar",
          "url": "concurrent-futures-1.1.0.jar",
          "size": 25987,
          "sha512": "3864ec1769828064e1002d4319ed5d275de29a54c6150f47decb5e2afff5b4216faa5eace49f6e95121bff580d07a3e4121c9fdbc84113694c86df4bd655214d",
          "sha256": "0ce067c514a0d1049d1bebdf709e344ed3266fe9744275682937cdcb13334e9e",
          "sha1": "50b7fb98350d5f42a4e49704b03278542293ba48",
          "md5": "409aee996eabfb4f23428b2d6026d6aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "concurrent-futures-1.1.0-sources.jar",
          "url": "concurrent-futures-1.1.0-sources.jar",
          "size": 19716,
          "sha512": "d65d21d00c60aee9b4a9039cfbfe5b6c262d83a86d6c108b634830648faf08fcf95a977f13c5a82e5ed18525ecdd47f659e9abcdb76c97487a5e11874db8140b",
          "sha256": "cc06fb6045a6c066f50e237a3c2126bc88c16d358a57b3612ba633c9f530b0a0",
          "sha1": "a27842adf6c42f3d80893bd46e1de4ac024218e7",
          "md5": "8d367d5caa04f4fe7716b81751450f3c"
        }
      ]
    }
  ]
}
