{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-1.7.0-multiplatform-sources.jar",
          "url": "runtime-1.7.0-multiplatform-sources.jar",
          "size": 383674,
          "sha512": "1bb8f74ff3c231a5393911b88fa8f5a954b3d483a784f0242079000dfd02bace90721fc694b96186a493ce56a16cfb39dc9401e01276bf8f9478aa7fd88310e3",
          "sha256": "7d373d2656c155cd171a64e3a8e0e8e0de4879b258a558f4bbecb6fd67f8149f",
          "sha1": "d2f7c81d736fccd529e5ef702b770ef11774b87a",
          "md5": "e30db99f96698e6637213a2732b5e43f"
        },
        {
          "name": "runtime-1.7.0-samples-sources.jar",
          "url": "runtime-1.7.0-samples-sources.jar",
          "size": 18077,
          "sha512": "7c9ec4ab0e4ecea7f153688409bdb0b65de9ef7153d0420bdf66eeb1924b4a1809a71ff3898c2c5b5f291931d3b0e81336f1e4dbcd9b758fb2ca0946b4698067",
          "sha256": "c37a8028aaa1a27bbf76b0a8860b83de9862f91ce50dc73aa664d59e9bb69f27",
          "sha1": "0d2df3dc588a4a4b55270410d282cf465375a5d7",
          "md5": "e4fb67ba16c53fdb838775cc16a2f284"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "runtime-1.7.0-versionMetadata.json",
          "size": 62487,
          "sha512": "271ef4ce0db429eece17abcd16043fda4a3b5842524d9516ab67233d94104d229ee2ad3480933ee36477e27f86831b6f525364b06ef6aa695b2110756e7b8911",
          "sha256": "ec9c38290de11d0e20c0c7d2605f5d95d550a37ab9573c8a491f2f4ab8390d74",
          "sha1": "9780e5a9d142e5e347a2183f9068d1fe8b93abae",
          "md5": "c9662392d902626a9b7419cddd27308c"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-metadata-1.7.0.jar",
          "url": "runtime-1.7.0.jar",
          "size": 764,
          "sha512": "dab4a94fc7eda019bca1d06a4057a61aecdc487f50bb19b8ac49ead521d2f91f74a0b8513465f5e7d333062e4419a93695a8fc8c3d2e3e9e4112fe6360365521",
          "sha256": "9f40ab0b8cf4e7cb0f593493c2ed96e7155d0e91eb592407597ecd61e2d5a054",
          "sha1": "39912aaa32797bd642aa4ef543a834c884143412",
          "md5": "377754d56814d9739a8332b2b1e65b8a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-kotlin-1.7.0-sources.jar",
          "url": "runtime-1.7.0-sources.jar",
          "size": 368647,
          "sha512": "4c1fef96ca4340de50cc7cf55f84c7b3019bdb378a95e27c86820a2d04f10cad8dc4eab52da599a59eb07034b57e90aed7b56ed85bb2a29acbfeb0404f3c4af5",
          "sha256": "6adbb68e286131bdc44ec43e923d1bfe2ccf74cf34658cd8e21b19f712961a30",
          "sha1": "6e382ee00a87411cc11c5d57b1843b640d6c23b5",
          "md5": "8e9330caa792014490fe30fefd81daa6"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-android/1.7.0/runtime-android-1.7.0.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-android/1.7.0/runtime-android-1.7.0.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../runtime-android/1.7.0/runtime-android-1.7.0.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-android",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-desktop/1.7.0/runtime-desktop-1.7.0.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-desktop/1.7.0/runtime-desktop-1.7.0.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-desktop",
        "version": "1.7.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../runtime-desktop/1.7.0/runtime-desktop-1.7.0.module",
        "group": "androidx.compose.runtime",
        "module": "runtime-desktop",
        "version": "1.7.0"
      }
    }
  ]
}