{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji2",
    "module": "emoji2-views-helper",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.2.0.aar",
          "url": "emoji2-views-helper-1.2.0.aar",
          "size": 21917,
          "sha512": "f93f48ca072dfe10289b790deb9703f3d313fa0457f37cbc92881d31428372178f74d1fa41fb6605ab3ccb41ad2f02b710e72fa319b92e82926c0b523d9e8ebd",
          "sha256": "7ffa4d464d9db259fca0cdb50fbd4ab63d6872bcda59468b9f7555504c7d5ac4",
          "sha1": "4a22802fc9e88ad232522f04a35d1fdc3e5b4df0",
          "md5": "1a4b6d516e641772360a3030d6feda7f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.2.0.aar",
          "url": "emoji2-views-helper-1.2.0.aar",
          "size": 21917,
          "sha512": "f93f48ca072dfe10289b790deb9703f3d313fa0457f37cbc92881d31428372178f74d1fa41fb6605ab3ccb41ad2f02b710e72fa319b92e82926c0b523d9e8ebd",
          "sha256": "7ffa4d464d9db259fca0cdb50fbd4ab63d6872bcda59468b9f7555504c7d5ac4",
          "sha1": "4a22802fc9e88ad232522f04a35d1fdc3e5b4df0",
          "md5": "1a4b6d516e641772360a3030d6feda7f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "emoji2-views-helper-1.2.0-sources.jar",
          "url": "emoji2-views-helper-1.2.0-sources.jar",
          "size": 17409,
          "sha512": "b5babc8d9ebcf9faa0d0f20464d97e2ee686058fc593b801289866d5c8221df83b7ac9415ddc18eccccb5e26e69d0eda1b147d6d60685183c2d6308689500507",
          "sha256": "ede24c021b055ab0bc287ce3ab784ab1fff3f336dae1ee9adae8b0d849e7b997",
          "sha1": "833c4c3f1564f35f7f62b810bf3e0eaf544ebc1f",
          "md5": "b7694abf3b882286206b7c00585bf461"
        }
      ]
    }
  ]
}