{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.startup",
    "module": "startup-runtime",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6918562"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "startup-runtime-1.0.0.aar",
          "url": "startup-runtime-1.0.0.aar",
          "size": 18477,
          "sha512": "68cc9d1cf70c0a24d88a2ac1ec5eec88cfbfe04bbace6e2a9468f1bf0f7c979812ac7b070722d14fa9c774d82a6cd05d0fcb2efd459937e4eecdf16c7140e6f4",
          "sha256": "ff081d2db7dd28aec59f74934c514fbaf4ae5aac5258495fe10d612a3622f876",
          "sha1": "2b09d1715e2c98428ea7420deaf65b73f6ba8212",
          "md5": "aa21a2b31f63f08a1129afc2440bd204"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "startup-runtime-1.0.0.aar",
          "url": "startup-runtime-1.0.0.aar",
          "size": 18477,
          "sha512": "68cc9d1cf70c0a24d88a2ac1ec5eec88cfbfe04bbace6e2a9468f1bf0f7c979812ac7b070722d14fa9c774d82a6cd05d0fcb2efd459937e4eecdf16c7140e6f4",
          "sha256": "ff081d2db7dd28aec59f74934c514fbaf4ae5aac5258495fe10d612a3622f876",
          "sha1": "2b09d1715e2c98428ea7420deaf65b73f6ba8212",
          "md5": "aa21a2b31f63f08a1129afc2440bd204"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "startup-runtime-1.0.0-sources.jar",
          "url": "startup-runtime-1.0.0-sources.jar",
          "size": 6479,
          "sha512": "31331767ae1441a63f620c67edbc2701b967d85d148f8aedd6f001921a39e95a1e356a97c5c5d7d4743d30782806e30edd2d1c902d481ccfbce182158e008dc9",
          "sha256": "1ebe8c69a38eaebc5052b5592031b542a5151dc57d50f2886e698d908dd57d83",
          "sha1": "1caeb57122c1e988047c3f5a98493a3a8c6d5f21",
          "md5": "3215ed72732d35158949dae7f0869980"
        }
      ]
    }
  ]
}
