{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.annotation",
    "module": "annotation-experimental",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-experimental-1.4.1.aar",
          "url": "annotation-experimental-1.4.1.aar",
          "size": 39841,
          "sha512": "44d69a703fde230636b6d61064836d30e09ad651750fd1f2cb68308f2fca522294f8c5d131d0109f8d84fa80bffa18048b19d4ad4bdd75f1b36bd3c719146fc5",
          "sha256": "6bd4c7c7476f8260cd3bdbb81183583e93fc9f790c27dea7dc314181cbf87aa0",
          "sha1": "7851235e2a16ce50270a74b555edaf9209b42864",
          "md5": "aca026e4fc7ff8660516af2e207c5c7c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-experimental-1.4.1.aar",
          "url": "annotation-experimental-1.4.1.aar",
          "size": 39841,
          "sha512": "44d69a703fde230636b6d61064836d30e09ad651750fd1f2cb68308f2fca522294f8c5d131d0109f8d84fa80bffa18048b19d4ad4bdd75f1b36bd3c719146fc5",
          "sha256": "6bd4c7c7476f8260cd3bdbb81183583e93fc9f790c27dea7dc314181cbf87aa0",
          "sha1": "7851235e2a16ce50270a74b555edaf9209b42864",
          "md5": "aca026e4fc7ff8660516af2e207c5c7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-experimental-1.4.1-sources.jar",
          "url": "annotation-experimental-1.4.1-sources.jar",
          "size": 5257,
          "sha512": "142d1caf755add0406c9529971d06d59ab450af75274649b9969cb30c3bfe6e0390adc05df96117b90c16fda1de4769c417f44652170581c73ea6ffe4b733fdf",
          "sha256": "783a221a7c1093ff8932053998a69a24489f7930806a32b55366108146d29c1d",
          "sha1": "4dc003cb3c5ff16a1c3d09f3d1f7ae7b2d14a9c4",
          "md5": "1350d8fbe13f314b76ba8161a066e46a"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "annotation-experimental-1.4.1-versionMetadata.json",
          "url": "annotation-experimental-1.4.1-versionMetadata.json",
          "size": 1287,
          "sha512": "3608a782fa88d6602da4470a8c7e386cf9f5591d731e78e66c1ade1b35b13f4f3973f8ab1f67b1d4663b8c0a9272a1d5ded2ed5d6ed26abe0be8263b3d46f0e3",
          "sha256": "0da5ae0db71a6cd50d34a3b6aa9509cf3589ca492bcb405d11695695a0a394af",
          "sha1": "b7b6e4f0996db83b61a1282b815e12220685c06f",
          "md5": "c915c7f080442a1854b48e0cc3efad35"
        }
      ]
    }
  ]
}