{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build.jetifier",
    "module": "jetifier-core",
    "version": "1.0.0-beta10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6794065"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "jetifier-core-1.0.0-beta10.jar",
          "url": "jetifier-core-1.0.0-beta10.jar",
          "size": 128988,
          "sha512": "7c87414a0753a7bc5e14c34acb9bec7911960ce7832e8b78825c0fa516631b4687b839b50ca938b75fbe439636b9a2823303b68cc52d36e9559ae750caa978fc",
          "sha256": "26abb4a13927d9062169c504c9e94fe80e9ae3a4f7b5ab8875ab007536a91f5e",
          "sha1": "6e621022a9c95af12a7004d6b55805bbd1126837",
          "md5": "45a718d6bdbf73f9450dec94c2880f6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "jetifier-core-1.0.0-beta10.jar",
          "url": "jetifier-core-1.0.0-beta10.jar",
          "size": 128988,
          "sha512": "7c87414a0753a7bc5e14c34acb9bec7911960ce7832e8b78825c0fa516631b4687b839b50ca938b75fbe439636b9a2823303b68cc52d36e9559ae750caa978fc",
          "sha256": "26abb4a13927d9062169c504c9e94fe80e9ae3a4f7b5ab8875ab007536a91f5e",
          "sha1": "6e621022a9c95af12a7004d6b55805bbd1126837",
          "md5": "45a718d6bdbf73f9450dec94c2880f6c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jetifier-core-1.0.0-beta10-sources.jar",
          "url": "jetifier-core-1.0.0-beta10-sources.jar",
          "size": 63596,
          "sha512": "917c783bf9e64a3bb743203fd453bc3b7680b132e88467d6d3e42412ace6d8dc6488931250c17ea113c66ad65bf50ea5dd882e0f9db1a3ae1998bca919444e33",
          "sha256": "9b86f5a3a70d14a27363d20526276917c18e5a9d479a4eb179c2763f494ae007",
          "sha1": "a848cd57e8f313f9f111429e2aaa3490e38635af",
          "md5": "d828bb73813a75e6a888bc7bdcc7876f"
        }
      ]
    }
  ]
}
