{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.paparazzi",
    "module": "paparazzi-gradle-plugin",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "paparazzi-gradle-plugin-1.3.4.jar",
          "url": "paparazzi-gradle-plugin-1.3.4.jar",
          "size": 90086,
          "sha512": "cca98bd113dd7fed0d0c9b6f8c2bfbfa821336f189ea2980000a32ab65e427a1ff5d19017502f028bc1685f7d44780c5c8561f23c31545989978387a339191d5",
          "sha256": "317b9c4174706eadf3525c705479e4a7b34a38fe5d54123a6822d7e5f1fa66ca",
          "sha1": "32f95dfa22e8745e2a4f05b0e2242432cc83c9bb",
          "md5": "d28aa4264eac6cb28fe906ffc4280a05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.9.24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.3.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.3.2"
          },
          "reason": "SymbolUtils.getPackageNameFromManifest removed in AGP 7.0.  Replace?"
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "paparazzi-gradle-plugin-1.3.4.jar",
          "url": "paparazzi-gradle-plugin-1.3.4.jar",
          "size": 90086,
          "sha512": "cca98bd113dd7fed0d0c9b6f8c2bfbfa821336f189ea2980000a32ab65e427a1ff5d19017502f028bc1685f7d44780c5c8561f23c31545989978387a339191d5",
          "sha256": "317b9c4174706eadf3525c705479e4a7b34a38fe5d54123a6822d7e5f1fa66ca",
          "sha1": "32f95dfa22e8745e2a4f05b0e2242432cc83c9bb",
          "md5": "d28aa4264eac6cb28fe906ffc4280a05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paparazzi-gradle-plugin-1.3.4-sources.jar",
          "url": "paparazzi-gradle-plugin-1.3.4-sources.jar",
          "size": 8416,
          "sha512": "4238832798d2bd0c0be3f73474d7d44341c95eae4fcae22eab8d343fe60e78d29d1dbc239420c59fcbf322fa4fcdc768f9a7ebeb9ab31bfc08b300e4d355e3f3",
          "sha256": "07554ba1f3b202b34150bda62972aab0c8cf2a129a9ab696beba1b9147e9710f",
          "sha1": "ebd2cc000061324a85ebeae8ef75ceef8fcdb27f",
          "md5": "cac27ff34f2fbfd5898b6cabb342b069"
        }
      ]
    }
  ]
}
