{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.moshi",
    "module": "moshi-kotlin",
    "version": "1.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "moshi-kotlin-1.15.1.jar",
          "url": "moshi-kotlin-1.15.1.jar",
          "size": 19519,
          "sha512": "5cf33d5550ade33c34c904eba766db1cc1e65cd524b17621cc92e3d798a7c93ecd2f8a7da10e3e22b315db4363ffb8a27e4db8565e1819e5019f8fc1325ce213",
          "sha256": "3c5a577200fc49a696647a52b1a97598a56d8d6f00e343ffed09d88b4007cdd0",
          "sha1": "9d76c17766ea84eaa36e9691fe156e702e189f23",
          "md5": "2725335b4ca4577c1ab6619356804180"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "moshi-kotlin-1.15.1.jar",
          "url": "moshi-kotlin-1.15.1.jar",
          "size": 19519,
          "sha512": "5cf33d5550ade33c34c904eba766db1cc1e65cd524b17621cc92e3d798a7c93ecd2f8a7da10e3e22b315db4363ffb8a27e4db8565e1819e5019f8fc1325ce213",
          "sha256": "3c5a577200fc49a696647a52b1a97598a56d8d6f00e343ffed09d88b4007cdd0",
          "sha1": "9d76c17766ea84eaa36e9691fe156e702e189f23",
          "md5": "2725335b4ca4577c1ab6619356804180"
        }
      ]
    }
  ]
}
