{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.23.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-metadata-1.9.0.jar",
          "url": "kotlinx-coroutines-core-1.9.0.jar",
          "size": 136423,
          "sha512": "3deaeaf7bbc80acd981b596c385bbee4e3778f086384252b141f78c67da16c55e24a6ca93169343b05c57bd79373792049b83f924ab990ff3b7399e4b5bb49c9",
          "sha256": "7089c33c145865020760d3dbca5e4634133cc3dd7feb926e830f6de6ede28ac6",
          "sha1": "6f3cbf4bb2e507b6be677d95f1f3113f7ee37eed",
          "md5": "3cff68455914ff19d63d5a3b4b8b9ea8"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinx-coroutines-core-kotlin-1.9.0-sources.jar",
          "url": "kotlinx-coroutines-core-1.9.0-sources.jar",
          "size": 327913,
          "sha512": "0708a25a6b19ee8505e5cd2bf3a66905e45e8df5104ee8d31ff9f3f58f772907a03be1358a4682c3ae1c4846b8322a6f7926ac4e7b36631405c72e7a10525a04",
          "sha256": "abd6b4a8588f6117f4ed2787c4ec7b2f9c25daa403b3b4bbcf26fa4e0a725398",
          "sha1": "5d533eb2fa0d6d6e46e1ab3d65ecd5b8a6bddc13",
          "md5": "7cc5988a66805dc80190d2236c82f7fc"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-androidnativearm32/1.9.0/kotlinx-coroutines-core-androidnativearm32-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-androidnativearm32",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-androidnativearm32/1.9.0/kotlinx-coroutines-core-androidnativearm32-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-androidnativearm32",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-androidnativearm64/1.9.0/kotlinx-coroutines-core-androidnativearm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-androidnativearm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-androidnativearm64/1.9.0/kotlinx-coroutines-core-androidnativearm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-androidnativearm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-androidnativex64/1.9.0/kotlinx-coroutines-core-androidnativex64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-androidnativex64",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-androidnativex64/1.9.0/kotlinx-coroutines-core-androidnativex64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-androidnativex64",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-androidnativex86/1.9.0/kotlinx-coroutines-core-androidnativex86-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-androidnativex86",
        "version": "1.9.0"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-androidnativex86/1.9.0/kotlinx-coroutines-core-androidnativex86-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-androidnativex86",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosarm64/1.9.0/kotlinx-coroutines-core-iosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosarm64/1.9.0/kotlinx-coroutines-core-iosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosarm64/1.9.0/kotlinx-coroutines-core-iosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iossimulatorarm64/1.9.0/kotlinx-coroutines-core-iossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iossimulatorarm64/1.9.0/kotlinx-coroutines-core-iossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iossimulatorarm64/1.9.0/kotlinx-coroutines-core-iossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosx64/1.9.0/kotlinx-coroutines-core-iosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosx64/1.9.0/kotlinx-coroutines-core-iosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosx64/1.9.0/kotlinx-coroutines-core-iosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-js/1.9.0/kotlinx-coroutines-core-js-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-js",
        "version": "1.9.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-js/1.9.0/kotlinx-coroutines-core-js-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-js",
        "version": "1.9.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-js/1.9.0/kotlinx-coroutines-core-js-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-js",
        "version": "1.9.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-jvm/1.9.0/kotlinx-coroutines-core-jvm-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-jvm",
        "version": "1.9.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-jvm/1.9.0/kotlinx-coroutines-core-jvm-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-jvm",
        "version": "1.9.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-jvm/1.9.0/kotlinx-coroutines-core-jvm-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-jvm",
        "version": "1.9.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-linuxarm64/1.9.0/kotlinx-coroutines-core-linuxarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-linuxarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-linuxarm64/1.9.0/kotlinx-coroutines-core-linuxarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-linuxarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-linuxx64/1.9.0/kotlinx-coroutines-core-linuxx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-linuxx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-linuxx64/1.9.0/kotlinx-coroutines-core-linuxx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-linuxx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-macosarm64/1.9.0/kotlinx-coroutines-core-macosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-macosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-macosarm64/1.9.0/kotlinx-coroutines-core-macosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-macosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-macosarm64/1.9.0/kotlinx-coroutines-core-macosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-macosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-macosx64/1.9.0/kotlinx-coroutines-core-macosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-macosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-macosx64/1.9.0/kotlinx-coroutines-core-macosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-macosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-macosx64/1.9.0/kotlinx-coroutines-core-macosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-macosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-mingwx64/1.9.0/kotlinx-coroutines-core-mingwx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-mingwx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-mingwx64/1.9.0/kotlinx-coroutines-core-mingwx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-mingwx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosarm64/1.9.0/kotlinx-coroutines-core-tvosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosarm64/1.9.0/kotlinx-coroutines-core-tvosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosarm64/1.9.0/kotlinx-coroutines-core-tvosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvossimulatorarm64/1.9.0/kotlinx-coroutines-core-tvossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvossimulatorarm64/1.9.0/kotlinx-coroutines-core-tvossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvossimulatorarm64/1.9.0/kotlinx-coroutines-core-tvossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosx64/1.9.0/kotlinx-coroutines-core-tvosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosx64/1.9.0/kotlinx-coroutines-core-tvosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosx64/1.9.0/kotlinx-coroutines-core-tvosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-wasm-js/1.9.0/kotlinx-coroutines-core-wasm-js-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-wasm-js",
        "version": "1.9.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-wasm-js/1.9.0/kotlinx-coroutines-core-wasm-js-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-wasm-js",
        "version": "1.9.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-wasm-js/1.9.0/kotlinx-coroutines-core-wasm-js-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-wasm-js",
        "version": "1.9.0"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-wasm-wasi/1.9.0/kotlinx-coroutines-core-wasm-wasi-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-wasm-wasi",
        "version": "1.9.0"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-wasm-wasi/1.9.0/kotlinx-coroutines-core-wasm-wasi-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-wasm-wasi",
        "version": "1.9.0"
      }
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-wasm-wasi/1.9.0/kotlinx-coroutines-core-wasm-wasi-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-wasm-wasi",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm32/1.9.0/kotlinx-coroutines-core-watchosarm32-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm32",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm32/1.9.0/kotlinx-coroutines-core-watchosarm32-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm32",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm32/1.9.0/kotlinx-coroutines-core-watchosarm32-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm32",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm64/1.9.0/kotlinx-coroutines-core-watchosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm64/1.9.0/kotlinx-coroutines-core-watchosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm64/1.9.0/kotlinx-coroutines-core-watchosarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosdevicearm64/1.9.0/kotlinx-coroutines-core-watchosdevicearm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosdevicearm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosdevicearm64/1.9.0/kotlinx-coroutines-core-watchosdevicearm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosdevicearm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosdevicearm64/1.9.0/kotlinx-coroutines-core-watchosdevicearm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosdevicearm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchossimulatorarm64/1.9.0/kotlinx-coroutines-core-watchossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchossimulatorarm64/1.9.0/kotlinx-coroutines-core-watchossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchossimulatorarm64/1.9.0/kotlinx-coroutines-core-watchossimulatorarm64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchossimulatorarm64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosx64/1.9.0/kotlinx-coroutines-core-watchosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosx64/1.9.0/kotlinx-coroutines-core-watchosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosx64",
        "version": "1.9.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosx64/1.9.0/kotlinx-coroutines-core-watchosx64-1.9.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosx64",
        "version": "1.9.0"
      }
    }
  ]
}
