{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-viewtree",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13070254"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-viewtree-1.0.0-sources.jar",
          "url": "core-viewtree-1.0.0-sources.jar",
          "size": 6342,
          "sha512": "67b777832fcdd988877865ae7e9e86b3411bf19cc5c0a072e9606ce8daa89245c596f6552eceae5b0c8523788c723616863fc2d6924c340504c2633c4f250b27",
          "sha256": "7026f2086f667720c43d4ca6bc58ab016d122ae0a404ca94e5fef6a7090e0984",
          "sha1": "479ee017137f7dbb52f0402e14b0f216e6b02bc6",
          "md5": "f3b6647e11a40b0218e52c321073b917"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-viewtree-1.0.0.aar",
          "url": "core-viewtree-1.0.0.aar",
          "size": 6980,
          "sha512": "a092ddcb247adf8c8bd215682e24fb6bcf577f0fb70d86190218a696b7fafbc525fa04fb2afd5f093daeca6d2cd74f42c3ed956c738ce101eac63af666e02b63",
          "sha256": "dc1b678d58ebcf2bfa1587be68ff826694ce3d221251b9ef30d4d4b36297e6de",
          "sha1": "449ba4f495b4d10d18edd01f32f9328be40d5749",
          "md5": "b8a098cdf97d6770dfd07d240d56aa73"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-viewtree-1.0.0.aar",
          "url": "core-viewtree-1.0.0.aar",
          "size": 6980,
          "sha512": "a092ddcb247adf8c8bd215682e24fb6bcf577f0fb70d86190218a696b7fafbc525fa04fb2afd5f093daeca6d2cd74f42c3ed956c738ce101eac63af666e02b63",
          "sha256": "dc1b678d58ebcf2bfa1587be68ff826694ce3d221251b9ef30d4d4b36297e6de",
          "sha1": "449ba4f495b4d10d18edd01f32f9328be40d5749",
          "md5": "b8a098cdf97d6770dfd07d240d56aa73"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-viewtree-1.0.0-versionMetadata.json",
          "url": "core-viewtree-1.0.0-versionMetadata.json",
          "size": 271,
          "sha512": "2a7e853c7eac4a17e6d83ef10d573368d92f65b6a2625a34a672e39e78bc2d5ba0ad2acfd3848e56522ec46a46ddd8bb1b8df7321b6f97906a28ae031aac14ae",
          "sha256": "ec403ba5468cd0ff58bec2290d8107e4f8ab8fce0941d8ce0459843ff591c8af",
          "sha1": "81ebb504e5596efb6b99311c6378233ba38d929d",
          "md5": "3bdc97ef8cbb5ecfdaa233d851f45fd6"
        }
      ]
    }
  ]
}