{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-1.2.0.aar",
          "url": "tracing-1.2.0.aar",
          "size": 6060,
          "sha512": "a82247792ca2585facbff6b3bdc66fe6d1953e453536816c75a180206bed7fe515da3244e98c10421a16d2bc140427df28a2464497dc2e3fc65ff17abe11c724",
          "sha256": "6faa90390d1fdbf0adb9a99bf99de67b94c6c6f35aea9510593a9d17973736a2",
          "sha1": "a6ac2cc501278fdc99c56b428548e0cd1e9300f7",
          "md5": "5bcd84db5a5ced2fcbbadf8cc1d9c8b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-1.2.0.aar",
          "url": "tracing-1.2.0.aar",
          "size": 6060,
          "sha512": "a82247792ca2585facbff6b3bdc66fe6d1953e453536816c75a180206bed7fe515da3244e98c10421a16d2bc140427df28a2464497dc2e3fc65ff17abe11c724",
          "sha256": "6faa90390d1fdbf0adb9a99bf99de67b94c6c6f35aea9510593a9d17973736a2",
          "sha1": "a6ac2cc501278fdc99c56b428548e0cd1e9300f7",
          "md5": "5bcd84db5a5ced2fcbbadf8cc1d9c8b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-1.2.0-sources.jar",
          "url": "tracing-1.2.0-sources.jar",
          "size": 6669,
          "sha512": "3636b4b1c41d48c446119695ec8790044e74d8798df26705810a469287a0e291b4fd9543e2811d5c244b754361ebcaa70f0537d666bdd6785222d5f6873dda47",
          "sha256": "3daf3a210e213f1675e6ea9ae2a9c0b9c837b42805835b65d999eca58fbddc90",
          "sha1": "7a8da514613e34b2f3cc6f1d9dc805295d9838a7",
          "md5": "b5ef389b90cc8492cd70bd525ace30b7"
        }
      ]
    }
  ]
}