{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.annotation",
    "module": "annotation",
    "version": "1.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "annotation-1.8.1-multiplatform-sources.jar",
          "url": "annotation-1.8.1-multiplatform-sources.jar",
          "size": 69592,
          "sha512": "f8c5adf841454dfc70ff44099b9beb667401811447e82c8b050f1cca7d7cd359b98d23dc8e94d844dbe89b61dd27baba455929f30a3a435fce34860177803984",
          "sha256": "1df309b2983afee24b4c95bc2f8e59e2df622881bc2696495b4479fcad79440f",
          "sha1": "61f06470a7951ebc7fb1f312039d2d83b4a235a0",
          "md5": "ffe77386e42cbd799d783c3faa00aca8"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "annotation-1.8.1-versionMetadata.json",
          "size": 10678,
          "sha512": "2a51c835086d56386317514850b6e248abc3132dfd27f2a82a96452ef16e98eb545456fbb63cc4949194754ea332ffd7413a115a24989358507202067a1fb004",
          "sha256": "f0beb8cc835fbaf4771de3467663db2c3e5fea01b30f632b1cd05a4d4fc2302f",
          "sha1": "679476fe1ddb88dbc9ae437123564b9916a2ad73",
          "md5": "d573b05e137581f480916230f06aee97"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-metadata-1.8.1.jar",
          "url": "annotation-1.8.1.jar",
          "size": 8290,
          "sha512": "aa2761bc4841457e4c57265038d7b96c4311377b6915f038713412f4c5bf58b8985d0aacc5f1b6d00c0585450fae3ccaea3a1dd6ae90177c7abdb47768e38f1b",
          "sha256": "fa5e67ffcc52a0413f4b39c2737b43c1ba6c6975b4bd4a4ea8627549e766285b",
          "sha1": "413c06dfa1779f733191e800108d6bfdefe1da8f",
          "md5": "897810e90a627e067abeecc57223d165"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "annotation-kotlin-1.8.1-sources.jar",
          "url": "annotation-1.8.1-sources.jar",
          "size": 25046,
          "sha512": "b6bc5c54cb62943ea645bbc272e279fc9a5c09a069eb5bfaae4f618ef20debabccec9354b4bed5c0527935c22f1f8b459e73544b2a9112fa72e37df3b1742022",
          "sha256": "706eb1c09bbc2ad74bf0f173e1fe77ac46fd7945efd9b6409053fb3f8763eff2",
          "sha1": "6e41c5bab9458ad24f11b7b58c54fbe17d9fc1b2",
          "md5": "d7b2ae4b5a2a3e3b353c1b8db09fab45"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-androidnativearm32/1.8.1/annotation-androidnativearm32-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-androidnativearm32",
        "version": "1.8.1"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-androidnativearm32/1.8.1/annotation-androidnativearm32-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-androidnativearm32",
        "version": "1.8.1"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-androidnativearm64/1.8.1/annotation-androidnativearm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-androidnativearm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-androidnativearm64/1.8.1/annotation-androidnativearm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-androidnativearm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-androidnativex64/1.8.1/annotation-androidnativex64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-androidnativex64",
        "version": "1.8.1"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-androidnativex64/1.8.1/annotation-androidnativex64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-androidnativex64",
        "version": "1.8.1"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-androidnativex86/1.8.1/annotation-androidnativex86-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-androidnativex86",
        "version": "1.8.1"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-androidnativex86/1.8.1/annotation-androidnativex86-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-androidnativex86",
        "version": "1.8.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosarm64/1.8.1/annotation-iosarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-iosarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosarm64/1.8.1/annotation-iosarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-iosarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosarm64/1.8.1/annotation-iosarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-iosarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iossimulatorarm64/1.8.1/annotation-iossimulatorarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-iossimulatorarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iossimulatorarm64/1.8.1/annotation-iossimulatorarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-iossimulatorarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iossimulatorarm64/1.8.1/annotation-iossimulatorarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-iossimulatorarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosx64/1.8.1/annotation-iosx64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-iosx64",
        "version": "1.8.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosx64/1.8.1/annotation-iosx64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-iosx64",
        "version": "1.8.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-iosx64/1.8.1/annotation-iosx64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-iosx64",
        "version": "1.8.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../annotation-jvm/1.8.1/annotation-jvm-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-jvm",
        "version": "1.8.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../annotation-jvm/1.8.1/annotation-jvm-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-jvm",
        "version": "1.8.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../annotation-jvm/1.8.1/annotation-jvm-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-jvm",
        "version": "1.8.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-linuxarm64/1.8.1/annotation-linuxarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-linuxarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-linuxarm64/1.8.1/annotation-linuxarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-linuxarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-linuxx64/1.8.1/annotation-linuxx64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-linuxx64",
        "version": "1.8.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-linuxx64/1.8.1/annotation-linuxx64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-linuxx64",
        "version": "1.8.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosarm64/1.8.1/annotation-macosarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-macosarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosarm64/1.8.1/annotation-macosarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-macosarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosarm64/1.8.1/annotation-macosarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-macosarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosx64/1.8.1/annotation-macosx64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-macosx64",
        "version": "1.8.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosx64/1.8.1/annotation-macosx64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-macosx64",
        "version": "1.8.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-macosx64/1.8.1/annotation-macosx64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-macosx64",
        "version": "1.8.1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvosarm64/1.8.1/annotation-tvosarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-tvosarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvosarm64/1.8.1/annotation-tvosarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-tvosarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvosarm64/1.8.1/annotation-tvosarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-tvosarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvossimulatorarm64/1.8.1/annotation-tvossimulatorarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-tvossimulatorarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvossimulatorarm64/1.8.1/annotation-tvossimulatorarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-tvossimulatorarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvossimulatorarm64/1.8.1/annotation-tvossimulatorarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-tvossimulatorarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvosx64/1.8.1/annotation-tvosx64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-tvosx64",
        "version": "1.8.1"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvosx64/1.8.1/annotation-tvosx64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-tvosx64",
        "version": "1.8.1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-tvosx64/1.8.1/annotation-tvosx64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-tvosx64",
        "version": "1.8.1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosarm32/1.8.1/annotation-watchosarm32-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosarm32",
        "version": "1.8.1"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosarm32/1.8.1/annotation-watchosarm32-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosarm32",
        "version": "1.8.1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosarm32/1.8.1/annotation-watchosarm32-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosarm32",
        "version": "1.8.1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosarm64/1.8.1/annotation-watchosarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosarm64/1.8.1/annotation-watchosarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosarm64/1.8.1/annotation-watchosarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchossimulatorarm64/1.8.1/annotation-watchossimulatorarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-watchossimulatorarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchossimulatorarm64/1.8.1/annotation-watchossimulatorarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-watchossimulatorarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchossimulatorarm64/1.8.1/annotation-watchossimulatorarm64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-watchossimulatorarm64",
        "version": "1.8.1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosx64/1.8.1/annotation-watchosx64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosx64",
        "version": "1.8.1"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosx64/1.8.1/annotation-watchosx64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosx64",
        "version": "1.8.1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotation-watchosx64/1.8.1/annotation-watchosx64-1.8.1.module",
        "group": "androidx.annotation",
        "module": "annotation-watchosx64",
        "version": "1.8.1"
      }
    }
  ]
}