{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build.jetifier",
    "module": "jetifier-processor",
    "version": "1.0.0-beta10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6794065"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-core",
          "version": {
            "requires": "1.0.0-beta10"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "org.jdom",
          "module": "jdom2",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "jetifier-processor-1.0.0-beta10.jar",
          "url": "jetifier-processor-1.0.0-beta10.jar",
          "size": 175068,
          "sha512": "5f7316f3fbb67ef1c8993be3343a8ae0e6e1363053c306beb43a4863185b8b614ea76f1b36e4d1acfbe4e8643f48af214ea2f988d7f53b9af088dbaed6a4987c",
          "sha256": "c5067a7b928237a1271a5e9cb5710e9f80b4973293945bc51e3a4c864ea4bfed",
          "sha1": "946c39eb0c052ff4f60a8939648a8b99af20d604",
          "md5": "fbd9dfdbdc29fba71cb5e394833ff164"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-core",
          "version": {
            "requires": "1.0.0-beta10"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "org.jdom",
          "module": "jdom2",
          "version": {
            "requires": "2.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "jetifier-processor-1.0.0-beta10.jar",
          "url": "jetifier-processor-1.0.0-beta10.jar",
          "size": 175068,
          "sha512": "5f7316f3fbb67ef1c8993be3343a8ae0e6e1363053c306beb43a4863185b8b614ea76f1b36e4d1acfbe4e8643f48af214ea2f988d7f53b9af088dbaed6a4987c",
          "sha256": "c5067a7b928237a1271a5e9cb5710e9f80b4973293945bc51e3a4c864ea4bfed",
          "sha1": "946c39eb0c052ff4f60a8939648a8b99af20d604",
          "md5": "fbd9dfdbdc29fba71cb5e394833ff164"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jetifier-processor-1.0.0-beta10-sources.jar",
          "url": "jetifier-processor-1.0.0-beta10-sources.jar",
          "size": 57754,
          "sha512": "673ffb488312805ffbf666e94f106cd2151663091d0ffe6bc7e6da03c44ab2257eff0fb59201328de37acd53413cc464273a98b43cd12657ff2a0967e63745de",
          "sha256": "535e86bd7967d7461bd2e5520649df271bfd6be15ea9a534ce7e3adcbe6ee616",
          "sha1": "54b89fdd8cd8258bbaed0ec043738a2a049b133a",
          "md5": "04edd143afba76a7b3a53815f407318c"
        }
      ]
    }
  ]
}
