{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "7.3.3"
    }
  },
  "component" : {
    "group" : "com.github.weliem",
    "module" : "blessed-android",
    "version" : "2.4.0",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "releaseVariantReleaseApiPublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "blessed-android-2.4.0.aar",
      "url" : "blessed-android-2.4.0.aar",
      "size" : 134045,
      "sha512" : "c939c4185627505699bbf53357e831708a4a3bca6f515bd8b76ff00ac741c0f4707bda2486d1e83359d919628bf1f569d56f16e8a75272b772cdcae2e4a5cc24",
      "sha256" : "e53008e28cb9a9227a79d621c73ffce1c377db0d66470f0268bdbce7a896d191",
      "sha1" : "3b6f1ecdb19675a3c64b02f3e29bb35c668fb6e1",
      "md5" : "e7068d7a5d141693ca45ee6b329f8677"
    } ]
  }, {
    "name" : "releaseVariantReleaseRuntimePublication",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.libraryelements" : "aar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "com.jakewharton.timber",
      "module" : "timber",
      "version" : {
        "requires" : "5.0.1"
      }
    }, {
      "group" : "org.jetbrains",
      "module" : "annotations",
      "version" : {
        "requires" : "20.1.0"
      }
    } ],
    "files" : [ {
      "name" : "blessed-android-2.4.0.aar",
      "url" : "blessed-android-2.4.0.aar",
      "size" : 134045,
      "sha512" : "c939c4185627505699bbf53357e831708a4a3bca6f515bd8b76ff00ac741c0f4707bda2486d1e83359d919628bf1f569d56f16e8a75272b772cdcae2e4a5cc24",
      "sha256" : "e53008e28cb9a9227a79d621c73ffce1c377db0d66470f0268bdbce7a896d191",
      "sha1" : "3b6f1ecdb19675a3c64b02f3e29bb35c668fb6e1",
      "md5" : "e7068d7a5d141693ca45ee6b329f8677"
    } ]
  } ]
}