{
  "formatVersion": "1.1",
  "component": {
    "url": "../../collection/1.4.2/collection-1.4.2.module",
    "group": "androidx.collection",
    "module": "collection",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.4.2"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.4.2.jar",
          "url": "collection-jvm-1.4.2.jar",
          "size": 775789,
          "sha512": "edbbf739d4e4800c3d130d89b7492b23fca0a31a42e073ff03c52cdd66b7d29f19fa4c2cf4058035de03a500663235fe875f3b6b319fb82c7aebd3ed6454765d",
          "sha256": "984ce9bd780055eafb8a105aca3f514686bf7b1b6272ec7c645a98ce40fc7db4",
          "sha1": "bc60b5568a66d765a9fe8e266fd0c6c727e0b50b",
          "md5": "df1d03b5c0f89676bda77d72fe1d7e59"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.4.2"
          },
          "reason": "collection is in atomic group androidx.collection"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.4.2.jar",
          "url": "collection-jvm-1.4.2.jar",
          "size": 775789,
          "sha512": "edbbf739d4e4800c3d130d89b7492b23fca0a31a42e073ff03c52cdd66b7d29f19fa4c2cf4058035de03a500663235fe875f3b6b319fb82c7aebd3ed6454765d",
          "sha256": "984ce9bd780055eafb8a105aca3f514686bf7b1b6272ec7c645a98ce40fc7db4",
          "sha1": "bc60b5568a66d765a9fe8e266fd0c6c727e0b50b",
          "md5": "df1d03b5c0f89676bda77d72fe1d7e59"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.4.2"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.4.2-sources.jar",
          "url": "collection-jvm-1.4.2-sources.jar",
          "size": 235172,
          "sha512": "9807f8be96f47ac165aa7a3ee1d03f9847f7f9dd1025bbdbfaefec2e2b6d876bc2fc264061887ab5bd5ea52491c7f2ce21ba289f32ad0bd990d98f24c745c01c",
          "sha256": "9cdb219ee75724515c232ae2bb04403c1fd1b40208c61d92aaa6452836d943c5",
          "sha1": "1391e2d73ea1c99d7b1350fce136ea1fcd32a893",
          "md5": "c503cc127205b6d702e19f18f17d8e40"
        }
      ]
    }
  ]
}