{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-android",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.7.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-android-1.7.3.jar",
          "url": "kotlinx-coroutines-android-1.7.3.jar",
          "size": 20637,
          "sha512": "e2ce7bcf67b10a2d3ae14dfb8defaa48f01c3145cfa2467f52913a3ea8718908d353e8764fb760bec913dd43a3f1919a2459be6858f91543f043cd0ccfdf0868",
          "sha256": "59fffb26bee12c32dadcfa5d420c2a7db85d3253518128b170efda726613256d",
          "sha1": "38d9cad3a0b03a10453b56577984bdeb48edeed5",
          "md5": "c3f2c0cfca5650dbc947f40e34a75448"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.7.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-android-1.7.3.jar",
          "url": "kotlinx-coroutines-android-1.7.3.jar",
          "size": 20637,
          "sha512": "e2ce7bcf67b10a2d3ae14dfb8defaa48f01c3145cfa2467f52913a3ea8718908d353e8764fb760bec913dd43a3f1919a2459be6858f91543f043cd0ccfdf0868",
          "sha256": "59fffb26bee12c32dadcfa5d420c2a7db85d3253518128b170efda726613256d",
          "sha1": "38d9cad3a0b03a10453b56577984bdeb48edeed5",
          "md5": "c3f2c0cfca5650dbc947f40e34a75448"
        }
      ]
    }
  ]
}
