{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.android.material",
    "module": "material",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.coordinatorlayout",
          "module": "coordinatorlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.resourceinspection",
          "module": "resourceinspection-annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.12.0.aar",
          "url": "material-1.12.0.aar",
          "size": 2323473,
          "sha512": "4a9ab746bd5eefbb68d111f1e0111d419eab8d5f44b20fe06fdade6f2ca5af35ab1fd1ceb7c3167f9c0dc089f9d5ba79e9be3779b2b784b7012020b582d3881d",
          "sha256": "4a672941b626b9ab91ae893ed22598ea53ad69125c858c0a59fa9b90daa5cb08",
          "sha1": "e493b7ac7fc4b8ca48527e0199f9961652711ac3",
          "md5": "28c4eed848faa4433509c7e3081336a6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.coordinatorlayout",
          "module": "coordinatorlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.resourceinspection",
          "module": "resourceinspection-annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.12.0.aar",
          "url": "material-1.12.0.aar",
          "size": 2323473,
          "sha512": "4a9ab746bd5eefbb68d111f1e0111d419eab8d5f44b20fe06fdade6f2ca5af35ab1fd1ceb7c3167f9c0dc089f9d5ba79e9be3779b2b784b7012020b582d3881d",
          "sha256": "4a672941b626b9ab91ae893ed22598ea53ad69125c858c0a59fa9b90daa5cb08",
          "sha1": "e493b7ac7fc4b8ca48527e0199f9961652711ac3",
          "md5": "28c4eed848faa4433509c7e3081336a6"
        }
      ]
    }
  ]
}
