{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.13.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.13.2.jar",
          "url": "builder-8.13.2.jar",
          "size": 15823022,
          "sha512": "89b08d1750d73cf45f1e6f7f2030b2b702eff7a3da88f3a9a9550a3641e280c5a3f1d506020d10fbcb6258063aeb858eeee955d68086f4d386d248a635dcbdda",
          "sha256": "7d393f8553120c7d7a869cb33c4279aad9485986773f63af97af08ea2e1ff37a",
          "sha1": "92e06fde9f28276c57c4c81eefce4e72ec9cefc9",
          "md5": "ff9952a7f710ad2fb3f27478ed63221d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.13.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.13.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.13.2"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.13.2"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.13.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.13.2"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.13.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.13.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.13.2.jar",
          "url": "builder-8.13.2.jar",
          "size": 15823022,
          "sha512": "89b08d1750d73cf45f1e6f7f2030b2b702eff7a3da88f3a9a9550a3641e280c5a3f1d506020d10fbcb6258063aeb858eeee955d68086f4d386d248a635dcbdda",
          "sha256": "7d393f8553120c7d7a869cb33c4279aad9485986773f63af97af08ea2e1ff37a",
          "sha1": "92e06fde9f28276c57c4c81eefce4e72ec9cefc9",
          "md5": "ff9952a7f710ad2fb3f27478ed63221d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.13.2-javadoc.jar",
          "url": "builder-8.13.2-javadoc.jar",
          "size": 341755,
          "sha512": "61c3c42e0d4ea91a8d288344e032fd297ac62f780fc72efe18a9cdde75786d9cd0922f1986c19ce784f5decb12cc984af0e4aaffc00ad15ecb54c99f053b19ba",
          "sha256": "8db65a3cd07e694dce4f3e3187226b13b06e4443a70b32e9fc6e7d8097e05b10",
          "sha1": "5ad1fa28ea5cc189c45557acd96ece965e1f1971",
          "md5": "0006a7f575364997db089cd1a268e8f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.13.2-sources.jar",
          "url": "builder-8.13.2-sources.jar",
          "size": 283788,
          "sha512": "8a74cbe6bbea1407e09bda70e4112adfa0d13544364d8a6a5b079ceaede5b586278dd7c7015d8a657b7f5149bc4d15d8e782cfd48476c2a8574ed2bf1260846b",
          "sha256": "46785fe800dfdc013dd3b294d4bfc57abf8e3880a3f47dd28d85ec9b47d0377d",
          "sha1": "e37aa442bbb41ee67979f0e2e4166a5321722b24",
          "md5": "8eaf23bafa6f1a6cdbcdb4f5a0d5e8da"
        }
      ]
    }
  ]
}
