{
  "formatVersion": "1.1",
  "component": {
    "group": "io.perfmark",
    "module": "perfmark-api",
    "version": "0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "perfmark-api-0.27.0.jar",
          "url": "perfmark-api-0.27.0.jar",
          "size": 6954,
          "sha512": "647b32d75928e44fe355c7f34696d886bd332aa76a6c457e5c90a57d28a8a00e04a5206cf9bba86037660b81eb3f5f82dee7a0dd61330be94f5a71313cf99fd3",
          "sha256": "c7b478503ec524e55df19b424d46d27c8a68aeb801664fadd4f069b71f52d0f6",
          "sha1": "f86f575a41b091786a4b027cd9c0c1d2e3fc1c01",
          "md5": "73bcc9c91e5b65c4f75b0567e7a5590f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "perfmark-api-0.27.0.jar",
          "url": "perfmark-api-0.27.0.jar",
          "size": 6954,
          "sha512": "647b32d75928e44fe355c7f34696d886bd332aa76a6c457e5c90a57d28a8a00e04a5206cf9bba86037660b81eb3f5f82dee7a0dd61330be94f5a71313cf99fd3",
          "sha256": "c7b478503ec524e55df19b424d46d27c8a68aeb801664fadd4f069b71f52d0f6",
          "sha1": "f86f575a41b091786a4b027cd9c0c1d2e3fc1c01",
          "md5": "73bcc9c91e5b65c4f75b0567e7a5590f"
        }
      ]
    }
  ]
}
