{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji2",
    "module": "emoji2",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker-samples",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-benchmark",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-1.3.0.aar",
          "url": "emoji2-1.3.0.aar",
          "size": 143474,
          "sha512": "e29de158918d633bb13af27d83312bd0b149db22fd8935511e422024ba7b87a700a03c9782ba9cd376e37852876781c9e0c4efb4bc20a30d8a784d68ed41a7d9",
          "sha256": "2bf23818b23a996ddaa1b5fd5bb32129daff6bbb2dce15166e2fccdd2010b1a5",
          "sha1": "37ed42991ddf77924510472dba632314aab1c9d9",
          "md5": "0c7fe9caa3baf3da7a709d7a812616e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker-samples",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-benchmark",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-1.3.0.aar",
          "url": "emoji2-1.3.0.aar",
          "size": 143474,
          "sha512": "e29de158918d633bb13af27d83312bd0b149db22fd8935511e422024ba7b87a700a03c9782ba9cd376e37852876781c9e0c4efb4bc20a30d8a784d68ed41a7d9",
          "sha256": "2bf23818b23a996ddaa1b5fd5bb32129daff6bbb2dce15166e2fccdd2010b1a5",
          "sha1": "37ed42991ddf77924510472dba632314aab1c9d9",
          "md5": "0c7fe9caa3baf3da7a709d7a812616e0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker-samples",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-benchmark",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-1.3.0-sources.jar",
          "url": "emoji2-1.3.0-sources.jar",
          "size": 57650,
          "sha512": "bc7fdaa283f590da3329bc4b80ebd18da770b628e69b09ed4e5e34a27a0f505a233f597700407f92e52e5a62bb50e534d1de80f9589539af1f3fb1895c4ffb96",
          "sha256": "cd9b28e11cc5b9dacb5187ce2db89f97650a4c71c6ccf0aaa41a68cf8863c409",
          "sha1": "788179fcab96cd6ec9a3e284e2a509545dc0fb8d",
          "md5": "bcd8a79fc734e129ba2caec4e6d8d065"
        }
      ]
    }
  ]
}