{
  "formatVersion" : "1.1",
  "component" : {
    "group" : "com.github.jwoglom",
    "module" : "pumpX2",
    "version" : "v1.8.6",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "createdBy" : {
    "gradle" : {
      "version" : "9.2.1"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "14",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "pumpx2-messages-v1.8.6.jar",
      "url" : "pumpx2-messages-v1.8.6.jar",
      "size" : 827355,
      "sha512" : "46b28d7eee99b3f526614035064c69e6499b1261be8b244f9aa5cd8618210f5ca7f654cbaebcf386654c9f84f518857025486a65fe27fa5e91a6864befdc878d",
      "sha256" : "78b49662748228a38b4b02ae88c104ccb5e71d1d31bfe67d539fbefca5c4745d",
      "sha1" : "1158ea46a82a6b79aeaac1bb7b9cf69132b749e1",
      "md5" : "f69bcb65b57dd5bbd5ae2d8dd220f440"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "14",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime"
    },
    "dependencies" : [ {
      "group" : "com.github.jwoglom.pumpX2",
      "module" : "pumpx2-shared",
      "version" : {
        "requires" : "v1.8.6"
      }
    }, {
      "group" : "androidx.annotation",
      "module" : "annotation",
      "version" : {
        "requires" : "1.9.1"
      }
    }, {
      "group" : "commons-codec",
      "module" : "commons-codec",
      "version" : {
        "requires" : "1.18.0"
      }
    }, {
      "group" : "org.apache.commons",
      "module" : "commons-lang3",
      "version" : {
        "requires" : "3.17.0"
      }
    }, {
      "group" : "org.json",
      "module" : "json",
      "version" : {
        "requires" : "20230618"
      }
    }, {
      "group" : "org.bouncycastle",
      "module" : "bcprov-jdk14",
      "version" : {
        "requires" : "1.77"
      }
    } ],
    "files" : [ {
      "name" : "pumpx2-messages-v1.8.6.jar",
      "url" : "pumpx2-messages-v1.8.6.jar",
      "size" : 827355,
      "sha512" : "46b28d7eee99b3f526614035064c69e6499b1261be8b244f9aa5cd8618210f5ca7f654cbaebcf386654c9f84f518857025486a65fe27fa5e91a6864befdc878d",
      "sha256" : "78b49662748228a38b4b02ae88c104ccb5e71d1d31bfe67d539fbefca5c4745d",
      "sha1" : "1158ea46a82a6b79aeaac1bb7b9cf69132b749e1",
      "md5" : "f69bcb65b57dd5bbd5ae2d8dd220f440"
    } ]
  }, {
    "name" : "sourcesElements",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "sources",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "pumpx2-messages-v1.8.6.jar",
      "url" : "pumpx2-messages-v1.8.6.jar",
      "size" : 464910,
      "sha512" : "86af6be1279d0012e0c3b6a214dda0707b473e7dbf16e372ba17f30468acc77886ab9eecb472da502fe972a2f6b632d10e95643f28a3d3042e1cc761ceffc9e6",
      "sha256" : "fadf1c4b4c0862c41f95d8c272b01e5b17ff3812c3442e4b669e3cc6e9a96acf",
      "sha1" : "d22f32f52ced60a1b2c4e24620ce49d6c3bab973",
      "md5" : "b03b3c2db78d28aae1327af6df799ea3"
    } ]
  }, {
    "name" : "shadowRuntimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "shadowed",
      "org.gradle.jvm.version" : "14",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "pumpx2-messages-v1.8.6.jar",
      "url" : "pumpx2-messages-v1.8.6.jar",
      "size" : 8126538,
      "sha512" : "84d4f43b21ab27b1c4665d78937779bc1c08404e31837a5fb2412b94e400fdfeecae2de7793b9d6a4bda53c350e68ef2192256360d29d7d8854abdc2edc4140d",
      "sha256" : "dc98f16b32d178dc35d2184eb9edf75338520e38aada7b021935c4d070c2536a",
      "sha1" : "6e309aca106a3e891eb5f21327b003435e57c731",
      "md5" : "2735ce54ac706dd1e2e4138544fe7487"
    } ]
  } ]
}