{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core",
    "version": "1.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.15.0-sources.jar",
          "url": "core-1.15.0-sources.jar",
          "size": 945720,
          "sha512": "3aed5be61ec6a35f616c591b684ba1f206fb28dc0b8a23bd5b333d5d6b8bc86b303e1551c81e938b6fd5cbea096017e795bb5a4cd29e1e0090924d2e6cf159f2",
          "sha256": "f56a83aa404e6bba2065b7bacfb18b38f070c8861068fed656dd04570644a0e3",
          "sha1": "04bcb58ebddcaf3068743f5d1141fe5824f3abf5",
          "md5": "9e77e38d9a4c56a4d7b658f291ca2d83"
        },
        {
          "name": "core-1.15.0-samples-sources.jar",
          "url": "core-1.15.0-samples-sources.jar",
          "size": 6272,
          "sha512": "924ae5a6b8388f097b80b00a2bb7e094f5c4bcbb08df69cdc15770e97b575e6ec8bc77dd4ac50d927fbad2bd22bf9d73622984b4a761d94ef86839c3e28f2a70",
          "sha256": "7b42513b7a33535365c4606d46e5dd9c0c747ed704bcdc39ae1db665c3d00b8d",
          "sha1": "7a746abb87119c59f68b3274f0692e3a0390a4aa",
          "md5": "96f5c93bc127f664fd6906f5045af6ba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.15.0.aar",
          "url": "core-1.15.0.aar",
          "size": 1336135,
          "sha512": "bbfe3e53b060988df5597d9251f6a2170ddcaf9b4e977c13c3da708d8452ac74efd7d3019852cce4ab72da6393312312ea2cbf9c7af476f1d3dba03cdd186214",
          "sha256": "432b85a1974076e14b487ece4a28c59a84f1b9efc3fc8be72cd7f05d32055e51",
          "sha1": "e8d4c7eeed12403fdd2d5ef29a00ebe946d530d6",
          "md5": "bfb5ff8c0fa49dfef21d0fcc3fca8474"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-testing",
          "version": {
            "requires": "1.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.15.0.aar",
          "url": "core-1.15.0.aar",
          "size": 1336135,
          "sha512": "bbfe3e53b060988df5597d9251f6a2170ddcaf9b4e977c13c3da708d8452ac74efd7d3019852cce4ab72da6393312312ea2cbf9c7af476f1d3dba03cdd186214",
          "sha256": "432b85a1974076e14b487ece4a28c59a84f1b9efc3fc8be72cd7f05d32055e51",
          "sha1": "e8d4c7eeed12403fdd2d5ef29a00ebe946d530d6",
          "md5": "bfb5ff8c0fa49dfef21d0fcc3fca8474"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-1.15.0-versionMetadata.json",
          "url": "core-1.15.0-versionMetadata.json",
          "size": 266381,
          "sha512": "112d35ec66b38596d0589fd5bd6cf0e533e6c6fb6251dd0ebebe1226b874df2368d8b8d6516b49ad1d2ad4cffd6382a091de198f189c1ce11c5bfdcb5706aaf9",
          "sha256": "eecbccc4b069320fb0ba3a4b0ad0fa5913bfea0c4ec601ef9ad2dc3f2b414e87",
          "sha1": "ba18f249bcf98cb6c2e7f7fa656afd358420cb0d",
          "md5": "7c00b8ca2a99b3373999d21ba30ad660"
        }
      ]
    }
  ]
}