{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-util",
    "version": "1.7.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-util-1.7.8-multiplatform-sources.jar",
          "url": "ui-util-1.7.8-multiplatform-sources.jar",
          "size": 13944,
          "sha512": "07c1e494636fed63c1ce0d13ab3b5c7a5aafda1cadf7880628960951925350e4692155aae02d8de182b8b7f706b1a6a8067d8f1263a8c32e5aa5209723d7addd",
          "sha256": "42e57d065c3f8587ee27e7eeea434212cfddd796c9a559afc858ff2748e2ded3",
          "sha1": "c67c79c84996d85a46bf1c891b18b9313db7aa34",
          "md5": "0ffc88ae83317cc92bef60c969dcec83"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ui-util-1.7.8-versionMetadata.json",
          "size": 6011,
          "sha512": "cd5dec6030f70c3ad0971f581e78306c23d115b6b39414acdfeb2ad6e0a5480f51a5562abe660bd3ff73420f05d8c1abb8c06a63bd030fa2b4053f34f84274b5",
          "sha256": "fa7292c2cb5146eded13061742c967281109eb80e08653359bd8ec800ba9b59e",
          "sha1": "0446429fcd9c537c4c52caaa4f852edeb3ede59e",
          "md5": "fb7496b549e1b73bedf937c377d7070d"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-util-metadata-1.7.8.jar",
          "url": "ui-util-1.7.8.jar",
          "size": 9043,
          "sha512": "24d75e37fc6304cde8e98438910e535ffd2fd886d519f19bb28cf067bc022e0fdb57c8b0e337284a1308cd66e93fc5cb9a67d2a7f678eae65fdfae78a2ef5333",
          "sha256": "25afa139ccbda2c33c6d9e7be3579e2ca9295f986e3b4f5b96297d6ce0fba86a",
          "sha1": "738e5b9407416c0822a0acc35ac9196ea99e0996",
          "md5": "f89076871bc3fcb595756d7e0ec19386"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.8"
          },
          "reason": "ui-util is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-util-kotlin-1.7.8-sources.jar",
          "url": "ui-util-1.7.8-sources.jar",
          "size": 13674,
          "sha512": "ce9c8336b8131560f1db9be310cf455d5d3f4129ace52b4881173a17145a3764161ee95bb52abc0fcfe8233e182a388c4994a30a14c98c192579e039b3549b4e",
          "sha256": "8003ebf491abe9cdf13203b2ef9709bbad5517476380a5b2aa39d13eb21222e1",
          "sha1": "b82d94b08458b97488a0dabef6d099aa744e5910",
          "md5": "514403361d22ac95090119f130b58b0c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-util-android/1.7.8/ui-util-android-1.7.8.module",
        "group": "androidx.compose.ui",
        "module": "ui-util-android",
        "version": "1.7.8"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-util-android/1.7.8/ui-util-android-1.7.8.module",
        "group": "androidx.compose.ui",
        "module": "ui-util-android",
        "version": "1.7.8"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-util-android/1.7.8/ui-util-android-1.7.8.module",
        "group": "androidx.compose.ui",
        "module": "ui-util-android",
        "version": "1.7.8"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-util-jvmstubs/1.7.8/ui-util-jvmstubs-1.7.8.module",
        "group": "androidx.compose.ui",
        "module": "ui-util-jvmstubs",
        "version": "1.7.8"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-util-jvmstubs/1.7.8/ui-util-jvmstubs-1.7.8.module",
        "group": "androidx.compose.ui",
        "module": "ui-util-jvmstubs",
        "version": "1.7.8"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-util-jvmstubs/1.7.8/ui-util-jvmstubs-1.7.8.module",
        "group": "androidx.compose.ui",
        "module": "ui-util-jvmstubs",
        "version": "1.7.8"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-util-linuxx64stubs/1.7.8/ui-util-linuxx64stubs-1.7.8.module",
        "group": "androidx.compose.ui",
        "module": "ui-util-linuxx64stubs",
        "version": "1.7.8"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-util-linuxx64stubs/1.7.8/ui-util-linuxx64stubs-1.7.8.module",
        "group": "androidx.compose.ui",
        "module": "ui-util-linuxx64stubs",
        "version": "1.7.8"
      }
    }
  ]
}