{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-compose",
    "version": "1.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1",
      "buildId:": "13096995"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.1"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.1"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.10.1-sources.jar",
          "url": "activity-compose-1.10.1-sources.jar",
          "size": 16146,
          "sha512": "4f5a38d65cbe38b117b9ddbaa4b58a283193e16d64a333e70a6bca33c021699acdbd03a172742faa1e83f7be751e3e2edec27985816c961133faad8b777c1453",
          "sha256": "d90a2c22431fcd2bdad4b2f3637c831ec8ea124376f46a9a341e98c969e0f9e0",
          "sha1": "1500484dd23a73adf5694945a21fa50b7a4c9270",
          "md5": "47f771b7e33d94a50c7990e33af13fcc"
        },
        {
          "name": "activity-compose-1.10.1-samples-sources.jar",
          "url": "activity-compose-1.10.1-samples-sources.jar",
          "size": 7854,
          "sha512": "77fe4b73cbf1d0beb9fb5ad91859e5d00093ae7063f1f966ed932a3dc59083a09dd5a7c490db0ce31584a507ee6c6761cae2cd86e85221360546e67c515d24cf",
          "sha256": "f407f42db5338bcd2b175a5f903022699983d64374477c46bbef441fa0588e87",
          "sha1": "47fa378780764e0c90ec26fcf05211137198bb91",
          "md5": "efab3826b7ba8ed96016a31d9055265d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.1"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.1"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.10.1.aar",
          "url": "activity-compose-1.10.1.aar",
          "size": 1061221,
          "sha512": "39da8618b380a6f3b156025d11c385231835b449610ecf486edd9ff923e6975d389bdb5ec9930d804473003cc1acc7b548f4d83fe4b7ee835d480ae7d7869bbb",
          "sha256": "f89af1b26ccc834634387c857c2dd4f4654d37650890039c527c2fed07db6a61",
          "sha1": "b206e253c9210674ca1af032099b620325d74946",
          "md5": "7190b9ef839aefaf5bd70e3c4874d583"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.1"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.1"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.10.1.aar",
          "url": "activity-compose-1.10.1.aar",
          "size": 1061221,
          "sha512": "39da8618b380a6f3b156025d11c385231835b449610ecf486edd9ff923e6975d389bdb5ec9930d804473003cc1acc7b548f4d83fe4b7ee835d480ae7d7869bbb",
          "sha256": "f89af1b26ccc834634387c857c2dd4f4654d37650890039c527c2fed07db6a61",
          "sha1": "b206e253c9210674ca1af032099b620325d74946",
          "md5": "7190b9ef839aefaf5bd70e3c4874d583"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.1"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.1"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.10.1-versionMetadata.json",
          "url": "activity-compose-1.10.1-versionMetadata.json",
          "size": 2849,
          "sha512": "5714546ad415b32edbb1dc605d8deb041da8d48f9823cfded05d8e80176bc1b9542ec55768e91234c0685e5af9dccc7dadfafb73c074f7afc87d2004929614fd",
          "sha256": "a2e99e3b71fe2216235503f9c6ef420ee0b5f2e00d5b5fa6204c9c84deacd0f6",
          "sha1": "a0b5712c680fb1972e3cb8a8adba23d6a21f0dc5",
          "md5": "02f5da63275fe8a3508de068f20dc5c7"
        }
      ]
    }
  ]
}