package com.jwoglom.wearx2.pumpcomm

enum class MsgCode {
    INIT_PUMP_COMM,
    SEND_PUMP_COMMAND,
    SEND_PUMP_COMMANDS_BULK,
    SEND_PUMP_COMMANDS_BUST_CACHE_BULK,
    SEND_PUMP_COMMAND_BOLUS,
    CACHED_PUMP_COMMANDS_BULK,


    DISCONNECT,
}