{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.collection",
    "module": "collection-ktx",
    "version": "1.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.4"
          },
          "reason": "collection-ktx is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-ktx-1.4.4.jar",
          "url": "collection-ktx-1.4.4.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.4"
          },
          "reason": "collection-ktx is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-ktx-1.4.4.jar",
          "url": "collection-ktx-1.4.4.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.4"
          },
          "reason": "collection-ktx is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-ktx-1.4.4-sources.jar",
          "url": "collection-ktx-1.4.4-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.4"
          },
          "reason": "collection-ktx is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-ktx-1.4.4-versionMetadata.json",
          "url": "collection-ktx-1.4.4-versionMetadata.json",
          "size": 3458,
          "sha512": "e8e734115b4078e0bed13854bc660403d5ec7ce97dc53e94b3cdaaeec504d9428efc2dcb5428c7a359579ef836164c03ff3fc00dafdaabb41b889b8ef9e2cab3",
          "sha256": "92711f60630f734bb9f42a331e62d2fc5cbdcb033e2f6264e1885d5b723fbf5f",
          "sha1": "cdf976b94590241e39b0e27265e366f5a7ab628d",
          "md5": "752a0fdb532bf8cd595fc4d548bb5d0e"
        }
      ]
    }
  ]
}