{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jakewharton.timber",
    "module": "timber",
    "version": "5.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "timber-5.0.1.aar",
          "url": "timber-5.0.1.aar",
          "size": 32329,
          "sha512": "37a3e784d2b72e7c60159a705b57157d8ef17fdc35d33aa6983d343ba95e9c6d04e2e4b6d6d4fece371c77b36c4bea5e7466fd91da757b176a9c887a3aa875b2",
          "sha256": "c6edddfcc8eff42a1604c8577fcfa4b4ffd9f252122c52ea36cfe7967f512f71",
          "sha1": "661f0d6dd1c4152b26c01322bf6273a1eb206e26",
          "md5": "b3aa481c134b03110b946567a8d29178"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "20.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "timber-5.0.1.aar",
          "url": "timber-5.0.1.aar",
          "size": 32329,
          "sha512": "37a3e784d2b72e7c60159a705b57157d8ef17fdc35d33aa6983d343ba95e9c6d04e2e4b6d6d4fece371c77b36c4bea5e7466fd91da757b176a9c887a3aa875b2",
          "sha256": "c6edddfcc8eff42a1604c8577fcfa4b4ffd9f252122c52ea36cfe7967f512f71",
          "sha1": "661f0d6dd1c4152b26c01322bf6273a1eb206e26",
          "md5": "b3aa481c134b03110b946567a8d29178"
        }
      ]
    }
  ]
}
