{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.7.0-sources.jar",
          "url": "appcompat-1.7.0-sources.jar",
          "size": 496408,
          "sha512": "9d37163ca4af0d2d13f87ce88bb9a3c19177de052c9d0b1facd4b1940997312b6dc07e625f6928b8bddde27f7746d4b27932f40a158bfb28446a5145d95e1891",
          "sha256": "6e3d3af46fbd9cb51ce6feb791274a9c2da11b64ba7b967a5dd12915e0aa031a",
          "sha1": "c66c25a939bfe4b18249922dc4e7a19caca8bf68",
          "md5": "acd13fd1ac2f647c1571e05aa01660af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.7.0.aar",
          "url": "appcompat-1.7.0.aar",
          "size": 1148962,
          "sha512": "27d808c54851431b0c74983b894ed9ecc36e561cf89afeb16ad0e40127f334b7828e618c7b74b8a552b9b7f1ce2691eb008a48f317f5c0a7b73691929af6af00",
          "sha256": "67189713b30a3fab6971713cc5fab1cb7f022bcf648a257563715c91d719d584",
          "sha1": "d44656e67ab2123393e5f3e957ecc3641a600c7b",
          "md5": "b717158e253ee555711bde7732be45a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.resourceinspection",
          "module": "resourceinspection-annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.7.0.aar",
          "url": "appcompat-1.7.0.aar",
          "size": 1148962,
          "sha512": "27d808c54851431b0c74983b894ed9ecc36e561cf89afeb16ad0e40127f334b7828e618c7b74b8a552b9b7f1ce2691eb008a48f317f5c0a7b73691929af6af00",
          "sha256": "67189713b30a3fab6971713cc5fab1cb7f022bcf648a257563715c91d719d584",
          "sha1": "d44656e67ab2123393e5f3e957ecc3641a600c7b",
          "md5": "b717158e253ee555711bde7732be45a2"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.7.0-versionMetadata.json",
          "url": "appcompat-1.7.0-versionMetadata.json",
          "size": 68799,
          "sha512": "f840c037d66127fcb433cd3ff717f08d9564a54d8214a151a8c7edfba35c877448a388d496c2affc17b357bf982d235f5b7fb66648048eb595651772428e3ce7",
          "sha256": "b4f30a3e42ab2a8b6207d3c844031c6f902219c9d82a7d81cfee50b189a0e426",
          "sha1": "90fbf696b0183171a76f336284a99053b846fc48",
          "md5": "1ed3883102d8fa1b4fd6e1a05d7837d7"
        }
      ]
    }
  ]
}